apiVersion: v1
kind: ConfigMap
metadata:
  name: quarkus-bad
data:
  bad.properties: |
    my.propr.1=toto
    my.propr.2=titi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quarkus-configmap
data:
  application.properties: |
    smallrye.config.locations=./secret/security.properties
    quarkus.log.level=INFO
    # quarkus.log.category."io.quarkus.configuration".level=TRACE
    # quarkus.log.category."io.quarkus.smallrye".level=TRACE
    quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/quarkus_test
    quarkus.hibernate-orm.database.generation=none
    quarkus.hibernate-orm.sql-load-script=no-file
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quarkus
  name: quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus
  template:
    metadata:
      labels:
        app: quarkus
    spec:
      containers:
      - name: quarkus
        image: sokube/quarkus-orm:v2
        imagePullPolicy: IfNotPresent
        # env:
        # - name: QUARKUS_LOG_LEVEL
        #   value: DEBUG
        # - name: QUARKUS_DATASOURCE_USERNAME
        #   value: quarkus_user
        # - name: QUARKUS_DATASOURCE_PASSWORD
        #   value: quarkus_pwd
        # - name: QUARKUS_DATASOURCE_JDBC_URL
        #   value: jdbc:postgresql://postgres:5432/quarkus_test
        # - name: QUARKUS_HIBERNATE-ORM_DATABASE_GENERATION
        #   value: none
        # - name: QUARKUS_HIBERNATE-ORM_SQL-LOAD-SCRIPT
        #   value: no-file
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: "10m"
            memory: "8Mi"
          limits:
            memory: "8Mi"
            cpu: "10m"
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: http
        #   failureThreshold: 5
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        #   timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: http
        #   failureThreshold: 5
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        #   timeoutSeconds: 10
        volumeMounts:
        - name: config-volume
          mountPath: /work/config
        - name: secret-volume
          mountPath: /work/secret
          readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: quarkus-configmap
        - name: secret-volume
          secret:
            secretName: quarkus-secret
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: quarkus
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quarkus
  annotations:
    kubernetes.io/ingress.class: traefik
    # traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: quarkus
            port:
              name: http
