apiVersion: v1
kind: Secret
metadata:
  name: quarkus-secret
  # annotations:
  #   sealedsecrets.bitnami.com/namespace-wide: "true" # -> for namespace-wide
  #   sealedsecrets.bitnami.com/cluster-wide: "true" # -> for cluster-wide
type: Opaque
stringData:
  security.properties: |-
    quarkus.datasource.username=quarkus_user
    quarkus.datasource.password=quarkus_pwd
# data:
#   security.properties: cXVhcmt1cy5kYXRhc291cmNlLnVzZXJuYW1lPXF1YXJrdXNfdXNlcgpxdWFya3VzLmRhdGFzb3VyY2UucGFzc3dvcmQ9cXVhcmt1c19wd2Q=
