apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  create.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
            CREATE SEQUENCE known_fruits_id_seq start 10 increment 1;
            CREATE TABLE known_fruits (id int4 not null, name varchar(40), primary key (id));
            INSERT INTO known_fruits(id, name) VALUES (1, 'Cherry');
            INSERT INTO known_fruits(id, name) VALUES (2, 'Apple');
            INSERT INTO known_fruits(id, name) VALUES (3, 'Banana');
    EOSQL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13.1-alpine
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_USER
            value: quarkus_user
          - name: POSTGRES_PASSWORD
            value: quarkus_pwd
          - name: POSTGRES_DB
            value: quarkus_test
        ports:
        - name: db
          containerPort: 5432
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: config-volume
          configMap:
            name: db-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - name: db
    port: 5432
    protocol: TCP
    targetPort: db
  selector:
    app: postgres
  sessionAffinity: None
  type: ClusterIP
